Repository PromoFaux/Matterhook.NET.MatterhookClient, pull requests merged in 2018-10, with the labels that each got.

#15 Added Message menus / Fix CI
  Matterhook.NET.MatterhookClient/IMattermostAction.cs
  Matterhook.NET.MatterhookClient/Matterhook.NET.MatterhookClient.csproj
  Matterhook.NET.MatterhookClient/MatterhookClient.cs
  Matterhook.NET.MatterhookClient/MattermostAttachment.cs
  Matterhook.NET.MatterhookClient/MattermostJsonSerializerSettings.cs
  Matterhook.NET.MatterhookClient/MattermostMessage.cs
  Matterhook.NET.MatterhookClient/MattermostMessageButton.cs
  Matterhook.NET.MatterhookClient/MattermostMessageMenu.cs
  Matterhook.NET.MatterhookClient/MattermostMessageMenuChannels.cs
  Matterhook.NET.MatterhookClient/MattermostMessageMenuUsers.cs
  Matterhook.NET.MatterhookClient/MessageMenuOption.cs
  Matterhook.NET.MatterhookClient/StringSplitter.cs
  README.md
  appveyor.yml
Labels: In Next Release, enhancement

#18 Check for invalid StringSplitter maxChunk
  Matterhook.NET.MatterhookClient/StringSplitter.cs
Labels: In Next Release, bug

#14 V1.4 release
  .gitignore
  ManualTests/Config.cs
  ManualTests/ManualTests.csproj
  ManualTests/Program.cs
  Matterhook.NET.MatterhookClient.sln
  Matterhook.NET.MatterhookClient/IMattermostAction.cs
  Matterhook.NET.MatterhookClient/Matterhook.NET.MatterhookClient.csproj
  Matterhook.NET.MatterhookClient/MatterhookClient.cs
  Matterhook.NET.MatterhookClient/MattermostAction.cs
  Matterhook.NET.MatterhookClient/MattermostAttachment.cs
  Matterhook.NET.MatterhookClient/MattermostField.cs
  Matterhook.NET.MatterhookClient/MattermostIntegration.cs
  Matterhook.NET.MatterhookClient/MattermostJsonSerializerSettings.cs
  Matterhook.NET.MatterhookClient/MattermostMessage.cs
  Matterhook.NET.MatterhookClient/MattermostMessageButton.cs
  Matterhook.NET.MatterhookClient/MattermostMessageMenu.cs
  Matterhook.NET.MatterhookClient/MattermostMessageMenuChannels.cs
  Matterhook.NET.MatterhookClient/MattermostMessageMenuUsers.cs
  Matterhook.NET.MatterhookClient/MessageMenuOption.cs
  Matterhook.NET.MatterhookClient/MessageSpec.cs
  Matterhook.NET.MatterhookClient/StringSplitter.cs
  README.md
  appveyor.yml
Labels: In Next Release
